QuestionWeb/QuestionWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from QuestionWeb import views

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')), #  追加
    path('', include('accounts.urls')), #"追加"
    path('admin/', admin.site.urls),
    path('edit/', include('edit.urls')),   # ←ここを追加
    path('question/', include('question.urls')),   # ←ここを追加
    path('', views.TopRefirectView.as_view(), name='top_redirect'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

QuestionWeb/edit/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.CategoryGroupList.as_view(), name='category_group_list'),
    path('category/list/<int:group_id>', views.CategoryList.as_view(), name='category_list'),
    path('question/list/', views.QuestionList.as_view(), name='question_list'),
    path('category_question/list/<int:category_id>', views.CategoryQuestionList.as_view(), name='category_question_list'),
    path('detail/<int:pk>/', views.QuestionDetail.as_view(), name='question_detail'),
    path('detail/<int:category_id>/<int:pk>/', views.QuestionDetail.as_view(), name='question_detail'),
    path('detail_img/<int:pk>/', views.ImageQuestionDetail.as_view(), name='question_detail_img'),
    path('detail_img/<int:category_id>/<int:pk>/', views.ImageQuestionDetail.as_view(), name='question_detail_img'),
    path('create/', views.QuestionCreateFormsetView.as_view(), name='question_create'),
    path('create_img/', views.ImageQuestionCreateFormsetView.as_view(), name='question_create_img'),
    path('update/<int:pk>', views.QuestionUpdateFormsetView.as_view(), name='question_update'),
    path('update_img/<int:pk>', views.ImageQuestionUpdateFormsetView.as_view(), name='question_update_img'),
    path('delete/<int:pk>', views.QuestionDeleteView.as_view(), name='question_delete'),
    path('delete_img/<int:pk>', views.ImageQuestionDeleteView.as_view(), name='question_delete_img'),
    path('question/add/<int:category_id>', views.QuestionAddView.as_view(), name='question_add'),
    path('question/add/<int:category_id>/<str:add_result>', views.QuestionAddView.as_view(), name='question_add'),
    path('question/exclusion/<int:category_id>', views.QuestionExclusionView.as_view(), name='question_exclusion'),
    path('question/exclusion/<int:category_id>/<str:exclusion_result>', views.QuestionExclusionView.as_view(), name='question_exclusion'),

    path('category/update/<int:group_id>/<int:pk>', views.CategoryUpdateView.as_view(), name='category_update'),
    path('category/create/<int:group_id>', views.CategoryCreateView.as_view(), name='category_create'),
    path('category/delete/<int:pk>', views.CategoryDeleteView.as_view(), name='category_delete'),

    path('category/sort/<int:pk>', views.CategoryGroupUpdateFormsetView.as_view(), name='category_sort'),

    

    
]

QuestionWeb/question/urls.py
from django.urls import path
from question import views

urlpatterns = [
    # 書籍
    path('question/<int:category_id>/<int:question_no>', views.QuestionView.as_view(), name='question'),
    path('category', views.CategoryView.as_view(), name='category'),
    path('answer_result/<int:category_id>/<int:question_id>/<int:question_no>/<str:question_type>/<int:choice_no>', views.AnswerResultView.as_view(), name='answer_result'),
    path('session_expire', views.SessionExpireView.as_view(), name='session_expire'),
    path('top', views.TopPageView.as_view(), name='top'),
    path('question/stop', views.QuestionStopView.as_view(), name='stop'),
    path('question/preparation', views.PreparationView.as_view(), name='preparation'),
    path('sample/answer/<str:question_type>/<int:question_id>', views.SampleAnswerView.as_view(), name='sample_answer'),
    path('help', views.HelpPageView.as_view(), name='help'),
]

QuestionWeb/question/models.py
from django.db import models

class CategoryGroup(models.Model):
    name = models.CharField('グループ名称', max_length=512, blank=False)

    def __str__(self):
        return self.name

def set_default_cateory_group():
    cateory_group, _ = CategoryGroup.objects.get_or_create(name='プリンセス別')
    return cateory_group.id

class Category(models.Model):
    name = models.CharField('カテゴリ名称', max_length=512, blank=False)
    category_no = models.PositiveSmallIntegerField(verbose_name='カテゴリNo.', default=1)
    CategoryGroup = models.ForeignKey(CategoryGroup, on_delete=models.CASCADE, default=set_default_cateory_group)
    img = models.ImageField(verbose_name='画像', upload_to='images/', null=True)

    def delete(self, using=None, keep_parents=False):
        self.img.delete()

        return super().delete(using, keep_parents)

    def save(self, *args, **kwargs):
        try:
            original_profile = Category.objects.get(pk=self.pk)
            if original_profile.img != self.img:
                original_profile.img.delete(save=False)

        except self.DoesNotExist:
            pass

        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

def set_default_disp_type():
    disp_type, _ = QuestionDispType.objects.get_or_create(name='左寄せ')
    return disp_type.id

class QuestionDispType(models.Model):
    name = models.CharField('表示形式名', max_length=512, blank=False)

    def __str__(self):
        return self.name


# Create your models here.
class Question(models.Model):
    body = models.CharField('本文（漢字）', max_length=1024)
    body_kana = models.CharField('本文（ひらがな）', max_length=1024, default="")
    Category = models.ManyToManyField(Category)
    question_no = models.PositiveSmallIntegerField(verbose_name='問題No.', default=0)
    answer_choice_no = models.PositiveSmallIntegerField(verbose_name='正解No.', default=1)
    ok_comment = models.CharField('解説（正解の場合）', max_length=1024, default="")
    ng_comment = models.CharField('解説（不正解の場合）', max_length=1024, default="")
    question_disp_type = models.ForeignKey(QuestionDispType, on_delete=models.SET_DEFAULT, default=set_default_disp_type)
    choice_type = models.CharField('選択肢のタイプ', max_length=1024, default="text")

    def __str__(self):
        return self.body

class TextChoice(models.Model):
    body = models.CharField('選択肢（漢字）', max_length=512)
    body_kana = models.CharField('選択肢（ひらがな）', max_length=1024, default="")
    Question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_no = models.PositiveSmallIntegerField(verbose_name='選択肢No.', default=1)

    def __str__(self):
        return self.body


class ImageQuestion(models.Model):
    body = models.CharField('本文（漢字）', max_length=1024)
    body_kana = models.CharField('本文（ひらがな）', max_length=1024, default="")
    Category = models.ManyToManyField(Category)
    question_no = models.PositiveSmallIntegerField(verbose_name='問題No.', default=0)
    answer_choice_no = models.PositiveSmallIntegerField(verbose_name='正解No.', default=1)
    ok_comment = models.CharField('解説（正解の場合）', max_length=1024, default="")
    ng_comment = models.CharField('解説（不正解の場合）', max_length=1024, default="")
    wrap_back_num = models.PositiveSmallIntegerField(verbose_name='1行の最大の選択肢数.', default=3)
    choice_type = models.CharField('選択肢のタイプ', max_length=1024, default="img")

    def __str__(self):
        return self.body

class ImageChoice(models.Model):
    img = models.ImageField(verbose_name = '画像', upload_to='images/', null=True)
    ImageQuestion = models.ForeignKey(ImageQuestion, on_delete=models.CASCADE)
    choice_no = models.PositiveSmallIntegerField(verbose_name='選択肢No.', default=1)

    def delete(self, using=None, keep_parents=False):
        self.img.delete()

        return super().delete(using, keep_parents)

    def save(self, *args, **kwargs):
        try:
            original_profile = ImageChoice.objects.get(pk=self.pk)
            if original_profile.img != self.img:
                original_profile.img.delete(save=False)

        except self.DoesNotExist:
            pass

        super().save(*args, **kwargs)

    def __str__(self):
        return self.body

QuestionWeb/question/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from question.models import Question, TextChoice, Category, ImageQuestion, CategoryGroup
import random
from django.http import HttpResponseRedirect
from django.shortcuts import reverse

# Create your views here.

QUESTION_MAX_QTY = 5

class TopPageView(TemplateView):
    template_name = "top.html"

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)

        sample_category = CategoryGroup.objects.get(name="サンプル問題").category_set.all().first() #サンプル問題カテゴリのみのはず。
        rand_int = random.randint(0, 1)

        # text優先
        if rand_int == 0:
            if sample_category.question_set.all().count() > 0:
                question_rand_int = rand_int = random.randint(0, sample_category.question_set.all().count() - 1)
                ctx['sample_question'] = sample_category.question_set.all()[question_rand_int]
                
            elif sample_category.imagequestion_set.all().count() > 0:
                question_rand_int = rand_int = random.randint(0, sample_category.imagequestion_set.all().count() - 1)
                ctx['sample_question'] = sample_category.imagequestion_set.all()[question_rand_int]

        #image優先
        elif rand_int == 1:
            if sample_category.imagequestion_set.all().count() > 0:
                question_rand_int = rand_int = random.randint(0, sample_category.imagequestion_set.all().count() - 1)
                ctx['sample_question'] = sample_category.imagequestion_set.all()[question_rand_int]
            elif sample_category.question_set.all().count() > 0:
                question_rand_int = rand_int = random.randint(0, sample_category.question_set.all().count() - 1)
                ctx['sample_question'] = sample_category.question_set.all()[question_rand_int]

        princess_group = CategoryGroup.objects.get(name="プリンセス別")
        ctx['princess_category_list'] = princess_group.category_set.all().order_by('category_no')

        difficulty_group = CategoryGroup.objects.get(name="難易度別")
        ctx['difficulty_category_list'] = difficulty_group.category_set.all().order_by('category_no')

        field_group = CategoryGroup.objects.get(name="分野別")
        ctx['field_category_list'] = field_group.category_set.all().order_by('category_no')

        return ctx


class QuestionView(TemplateView):
    template_name = "question_main.html"

    def get(self, request, **kwargs):
        
        question_no = kwargs.get('question_no')
        category_id = kwargs.get('category_id')

        question_qty = Category.objects.get(pk=category_id).question_set.all().count()
        question_qty += Category.objects.get(pk=category_id).imagequestion_set.all().count()

        if question_qty < QUESTION_MAX_QTY:
            return HttpResponseRedirect(reverse('preparation'))

        # セッション切れチェック
        if question_no == 1 and self.request.session.get('is_question_end', False) == False:
            self.request.session.clear() # 上限前に別カテゴリの問題に挑戦した場合はクリア

        elif question_no != 1 and not self.request.session.get('question_id_list', False):
            return HttpResponseRedirect(reverse('session_expire'))

        elif self.request.session.get('is_question_end', False):
            return HttpResponseRedirect(reverse('stop'))

        return super().get(request, **kwargs)

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)

        random_question_id_list = []
        category = Category.objects.get(pk=self.kwargs.get('category_id'))

        if not self.request.session.get('question_id_list', False):
            for q in category.question_set.all():
                random_question_id_list.append({'text' : q.id})
            
            for q in category.imagequestion_set.all():
                random_question_id_list.append({'img' : q.id})

            random.shuffle(random_question_id_list)
            
            self.request.session['question_id_list'] = random_question_id_list
            
        
        question_id_list = self.request.session.get('question_id_list')
        q_no = self.kwargs.get('question_no')

        rem_question_id_list = question_id_list[(q_no-1):]

        question_list = []

        for q_id_dic in rem_question_id_list:
            if 'text' in q_id_dic:
                question_list.append(Question.objects.get(pk=q_id_dic['text']))
            elif 'img' in q_id_dic:
                question_list.append(ImageQuestion.objects.get(pk=q_id_dic['img']))

        ctx['category'] = category

        ctx['question_list'] = question_list
        ctx['rem_res_cnt'] = QUESTION_MAX_QTY - self.request.session.get('res_cnt', 0)
        ctx['res_cnt'] = self.request.session.get('res_cnt', 0)

        return ctx

    def __get_text_question_id(self, random_question_id_list, category):
        question_list = category.question_set.all()

        for i in range(question_list.count()):
            rand_int = random.randint(0, question_list.count() - 1)
            rand_question = question_list[rand_int]

            if self.__is_selected(random_question_id_list, 'text', rand_question) == False:
                return rand_question.id
        
        return None

    def __get_img_question_id(self, random_question_id_list, category):
        question_list = category.imagequestion_set.all()

        for i in range(question_list.count()):
            rand_int = random.randint(0, question_list.count() - 1)
            rand_question = question_list[rand_int]

            if self.__is_selected(random_question_id_list, 'img', rand_question) == False:
                return rand_question.id
        
        return None

    
    def __is_selected(self, random_question_id_list, key, question):
        
        for rand_question_id_dict in random_question_id_list:
            if rand_question_id_dict.get(key) == question.id:
                return True

        return False

class QuestionStopView(TemplateView):
    template_name = "question_stop.html"

class CategoryView(TemplateView):
    template_name = "category.html"

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        
        category_list = Category.objects.all()

        ctx['category_list'] = category_list

        return ctx

class AnswerResultView(TemplateView):
    template_name = "question_comment.html"

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        
        if self.kwargs.get('question_type') == 'text':
            question = Question.objects.get(pk=self.kwargs.get('question_id'))
        elif self.kwargs.get('question_type') == 'img':
            question = ImageQuestion.objects.get(pk=self.kwargs.get('question_id'))

        answer_choice_no = question.answer_choice_no

        ctx['answer_choice_no'] = answer_choice_no
        ctx['choice_no'] = self.kwargs.get('choice_no')
        ctx['question'] = question
        ctx['category_id'] = self.kwargs.get('category_id')

        res_cnt = self.request.session.get('res_cnt', 0)
        res_cnt += 1
        self.request.session['res_cnt'] = res_cnt

        if res_cnt >= QUESTION_MAX_QTY:
            self.request.session['is_question_end'] = True

        return ctx

class SessionExpireView(TemplateView):
    template_name = "session_expire.html"

class PreparationView(TemplateView):
    template_name = "question_preparation.html"

class SampleAnswerView(TemplateView):
    template_name = "sample_answer.html"

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        
        if self.kwargs.get('question_type') == 'text':
            question = Question.objects.get(pk=self.kwargs.get('question_id'))
        elif self.kwargs.get('question_type') == 'img':
            question = ImageQuestion.objects.get(pk=self.kwargs.get('question_id'))

        ctx['princess_category'] = Category.objects.get(name="シンデレラ")
        ctx['question'] = question

        return ctx


class HelpPageView(TemplateView):
    template_name = "help.html"

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        
        

        return ctx

QuestionWeb/question/templates/category.html
{% extends "base.html" %}
{% block meta_title %}カテゴリ一覧{% endblock %}
{% block page_title %}カテゴリ一覧{% endblock %}
{% block content %}

{{ question.body }}

{% for category in category_list %}
    <p><a href="{% url 'question' category.id 1 %}">{{ category.name }}</a></p>
{% endfor %}


{% endblock %}

{% block js %}
{% endblock %}

QuestionWeb/question/templates/sample_answer.html
{% extends "base.html" %}
{% block meta_title %}QutyPie-Quiz|サンプル問題 正解{% endblock %}

{% load static %}
{% block css %}
<link href="{% static 'sample_answer.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div id="main">
    <div class="container">
        <div class="card mx-auto border-light question_card">
            <div class="card-body">
                <div class="row" id="main_row">
                    <div class="col text-center" id="main_message">
                        <p><b>{{ question.ng_comment }}</b></p>
                    </div>
                </div>
                <div class="row" id="sample_choice">
                    <div class="col-12">
                    
                        {% if question.textchoice_set.all %}
                        <div class="row">
                            {% if question.question_disp_type.name == '左寄せ' %}
                            <div class="col text-left">
                            {% else %}
                            <div class="col text-center">
                            {% endif %}
                        {% endif %}
                        {% for choice in question.textchoice_set.all %}
                        {% if forloop.counter == question.answer_choice_no %}
                            <div class="sample_text_choice">{{ forloop.counter }}.&nbsp;{{ choice.body }}</div>
                        {% endif %}
                        
                        {% endfor %}
            
                        {% if question.textchoice_set.all %}
                            </div>
                        </div>
                        {% endif %}
                        
                        {% if question.imagechoice_set.all %}
                        <div class="d-flex justify-content-center">
                        {% endif %}
                        {% for choice in question.imagechoice_set.all %}
                            {% if forloop.counter == question.answer_choice_no %}
                                <div><img src="/media/{{ choice.img }}" class="choice_image"></div>
                            {% endif %}
                        {% endfor %}
                        {% if question.imagechoice_set.all %}
                        </div>
                        {% endif %}
                    </div>
                </div>

                <div class="row">
                    <div class="col text-center">
                        <a id="next_btn" class="btn" href="{% url 'question' princess_category.pk 1 %}" role="button"><b>シンデレラのもんだいをはじめる！</b></a>
                    </div>
                </div>

                <div class="row" id="home_link_row">
                    <div class="col text-center">
                        <a id="home_link" href="{% url 'top' %}">> ホームに戻る</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block footer %}
<div class="container">
    <div class="row justify-content-center banner_row">
        <div class="card border-light banner_sp d-md-none d-block">
            <img class="card-img" src="{% static "banner_sp.png" %}" alt="">
            <div class="card-img-overlay">
            <h4 class="text-white"><b>バナー</b></h4>
            </div>
        </div>

        <div class="card border-light banner_pc d-none d-md-block">
            <img class="card-img" src="{% static "banner.png" %}" alt="">
            <div class="card-img-overlay">
            <h4 class="text-white"><b>バナー</b></h4>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block js %}
{% endblock %}

QuestionWeb/question/templates/top.html
{% extends "base.html" %}
{% block meta_title %}QutyPie-Quiz|トップ{% endblock %}

{% load static %}

{% block css %}
<link href="{% static 'top.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="jumbotron d-md-none d-block sp_bg">
    <div class="container-fluid">
      <div class="row" id="sample_question">
        <div class="col-12"><h2 class="text-center"><b>Q:{{ sample_question.body }}</b></h2></div>
      </div>
      <div class="row" id="sample_choice">
        <div class="col-12">
          
            {% if sample_question.textchoice_set.all %}
              <div class="row">
                {% if sample_question.question_disp_type.name == '左寄せ' %}
                  <div class="col text-left">
                {% else %}
                  <div class="col text-center">
                {% endif %}
            {% endif %}
            {% for choice in sample_question.textchoice_set.all %}
              <div class="sample_text_choice">{{ forloop.counter }}.&nbsp;{{ choice.body }}</div>
            {% endfor %}

            {% if sample_question.textchoice_set.all %}
                </div>
              </div>
            {% endif %}
            
            {% if sample_question.imagechoice_set.all %}
              <div class="d-flex justify-content-center">
            {% endif %}
            {% for choice in sample_question.imagechoice_set.all %}
              
                <div><img src="/media/{{ choice.img }}" class="choice_image"></div>

                {% if forloop.counter == sample_question.imagechoice_set.all|length %}
                  
                {% endif %}
            {% endfor %}
            {% if sample_question.imagechoice_set.all %}
              </div>
            {% endif %}
        </div>
      </div>
      <div class="row" id="sample_answer">
        {% if sample_question.textchoice_set.all %}
          <div class="col-12"><h5 class="text-right"><b><a href="{% url 'sample_answer' 'text' sample_question.pk %}">正解を見る</a></b></h5></div>
        {% elif sample_question.imagechoice_set.all %}
          <div class="col-12"><h5 class="text-right"><b><a href="{% url 'sample_answer' 'img' sample_question.pk %}">正解を見る</a></b></h5></div>
        {% endif %}
      </div>
    </div>
</div>

<div class="jumbotron d-none d-md-block pc_bg">
    <div class="container-fluid">
      <div class="row" id="sample_question">
        <div class="col-12"><h2 class="text-center"><b>Q:{{ sample_question.body }}</b></h2></div>
      </div>
      <div class="row" id="sample_choice">
        <div class="col-12">
          
            {% if sample_question.textchoice_set.all %}
              <div class="row">
                <div class="col-3"></div>
                {% if sample_question.question_disp_type.name == '左寄せ' %}
                  <div class="col-6 text-left">
                {% else %}
                  <div class="col-6 text-center">
                {% endif %}
                <div class="col-3"></div>
            {% endif %}
            {% for choice in sample_question.textchoice_set.all %}
            
              <div class="sample_text_choice"><p>{{ forloop.counter }}. {{ choice.body }}</p></div>
            {% endfor %}

            {% if sample_question.textchoice_set.all %}
                </div>
              </div>
            {% endif %}
            
            {% if sample_question.imagechoice_set.all %}
              <div class="d-flex justify-content-center">
            {% endif %}
            {% for choice in sample_question.imagechoice_set.all %}
              
                <div><img src="/media/{{ choice.img }}" class="choice_image"></div>

                {% if forloop.counter == sample_question.imagechoice_set.all|length %}
                  
                {% endif %}
            {% endfor %}
            {% if sample_question.imagechoice_set.all %}
              </div>
            {% endif %}
        </div>
      </div>
      <div class="row" id="sample_answer">
        {% if sample_question.textchoice_set.all %}
          <div class="col-12"><h5 class="text-center"><b><a href="{% url 'sample_answer' 'text' sample_question.pk %}">正解を見る</a></b></h5></div>
        {% elif sample_question.imagechoice_set.all %}
          <div class="col-12"><h5 class="text-center"><b><a href="{% url 'sample_answer' 'img' sample_question.pk %}">正解を見る</a></b></h5></div>
        {% endif %}
        
      </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row category_bar_rap">
        <div class="d-flex justify-content-center align-items-center">
            <div><img src="{% static "category_bar.png" %}" alt="" class="img-fluid category_bar_left"></div>
            <div><img src="{% static "category_icon.png" %}" alt="" class="category_bar_icon"></div>
            <div class="category_name"><h4><b>プリンセス別</b></h4></div>
            <div><img src="{% static "category_icon.png" %}" alt="" class="category_bar_icon"></div>
            <div><img src="{% static "category_bar.png" %}" alt="" class="img-fluid category_bar_right"></div>
        </div>
    </div>
</div>

<div class="container sp_category_icons d-md-none d-block">
    <div class="row justify-content-center category_icon_raw">

    {% for princess_category in princess_category_list %}
        <div class="card category_icon_rap border-light">
            <a href="{% url 'question' princess_category.pk 1 %}">
                <img class="card-img" src="/media/{{ princess_category.img }}" alt="">
                <div class="card-img-overlay">
                <h4 class="text-white"><b>{{ princess_category.name }}</b></h4>
                </div>
            </a>
        </div>
        
        {% if forloop.counter|divisibleby:2 %}
            </div>
            <div class="row justify-content-center category_icon_raw">
        {% endif %}
    {% endfor %}
    </div>
</div>

<div class="container pc_category_icons d-none d-md-block">
    <div class="row justify-content-center category_icon_raw">

        {% for princess_category in princess_category_list %}
            <div class="card category_icon_rap border-light">
                <a href="{% url 'question' princess_category.pk 1 %}">
                    <img class="card-img" src="/media/{{ princess_category.img }}" alt="">
                    <div class="card-img-overlay">
                    <h4 class="text-white"><b>{{ princess_category.name }}</b></h4>
                    </div>
                </a>
            </div>
            
            {% if forloop.counter|divisibleby:4 %}
                </div>
                <div class="row justify-content-center category_icon_raw">
            {% endif %}
        {% endfor %}
        </div>
    
</div>

<div class="container-fluid">
    <div class="row category_bar_rap">
        <div class="d-flex justify-content-center align-items-center">
            <div><img src="{% static "category_bar.png" %}" alt="" class="img-fluid category_bar_left"></div>
            <div><img src="{% static "category_icon.png" %}" alt="" class="category_bar_icon"></div>
            <div class="category_name"><h4><b>難易度別</b></h4></div>
            <div><img src="{% static "category_icon.png" %}" alt="" class="category_bar_icon"></div>
            <div><img src="{% static "category_bar.png" %}" alt="" class="img-fluid category_bar_right"></div>
        </div>
    </div>

    <div class="row justify-content-center nanido_bunya_row">
        {% for difficulty_category in difficulty_category_list %}
            <div class="card buya_card border-light">
                <a href="{% url 'question' difficulty_category.pk 1 %}">
                    <img class="card-img bunya" src="/media/{{ difficulty_category.img }}" alt="">
                    <div class="card-img-overlay">
                        <h4 class="text-white"><b>{{ difficulty_category.name }}</b></h4>
                    </div>
                </a>
            </div>
            
            {% if forloop.counter|divisibleby:4 %}
                </div>
                <div class="row justify-content-center nanido_bunya_row">
            {% endif %}
        {% endfor %}
        </div>
    
    <div class="row category_bar_rap">
        <div class="d-flex justify-content-center align-items-center">
            <div><img src="{% static "category_bar.png" %}" alt="" class="img-fluid category_bar_left"></div>
            <div><img src="{% static "category_icon.png" %}" alt="" class="category_bar_icon"></div>
            <div class="category_name"><h4><b>分野別</b></h4></div>
            <div><img src="{% static "category_icon.png" %}" alt="" class="category_bar_icon"></div>
            <div><img src="{% static "category_bar.png" %}" alt="" class="img-fluid category_bar_right"></div>
        </div>
    </div>

    <div class="row justify-content-center nanido_bunya_row">

        {% for field_category in field_category_list %}
            <div class="card buya_card border-light">
                <a href="{% url 'question' field_category.pk 1 %}">
                    <img class="card-img bunya" src="/media/{{ field_category.img }}" alt="">
                    <div class="card-img-overlay">
                        <h4 class="text-white"><b>{{ field_category.name }}</b></h4>
                    </div>
                </a>
            </div>
            
            {% if forloop.counter|divisibleby:4 %}
                </div>
                <div class="row justify-content-center nanido_bunya_row">
            {% endif %}
        {% endfor %}
        </div>

    <div class="row justify-content-center banner_row">
        <div class="card border-light banner_sp d-md-none d-block">
            <img class="card-img" src="{% static "banner_sp.png" %}" alt="">
            <div class="card-img-overlay">
            <h4 class="text-white"><b>バナー</b></h4>
            </div>
        </div>

        <div class="card border-light banner_pc d-none d-md-block">
            <img class="card-img" src="{% static "banner.png" %}" alt="">
            <div class="card-img-overlay">
            <h4 class="text-white"><b>バナー</b></h4>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block footer %}
<div class="jumbotron d-none d-md-block pc_footer_bg">
    <div class="container-fluid">
      <div class="row">
        <div class="col-12"><br><h3 class="text-center"><b>次世代のプリンセスに</b></h3></div>
      </div>
      <div class="row">
        <div class="col-12"><h3 class="text-center"><b>教養を</b></h3><br></div>
      </div>
    </div>
  </div>

  <div class="jumbotron d-md-none d-block sp_footer_bg">
    <div class="container-fluid">
      <div class="row">
        <div class="col-12"><br><h3 class="text-center sp_footer_text"><b>次世代のプリンセスに</b></h3></div>
      </div>
      <div class="row">
        <div class="col-12"><h3 class="text-center sp_footer_text"><b>教養を</b></h3><br></div>
      </div>
    </div>
  </div>

{% endblock %}

{% block js %}

{% endblock %}