QuestionWeb/QuestionWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from QuestionWeb import views

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')), #  追加
    path('', include('accounts.urls')), #"追加"
    path('admin/', admin.site.urls),
    path('edit/', include('edit.urls')),   # ←ここを追加
    path('question/', include('question.urls')),   # ←ここを追加
    path('', views.TopRefirectView.as_view(), name='top_redirect'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

QuestionWeb/edit/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.CategoryGroupList.as_view(), name='category_group_list'),
    path('category/list/<int:group_id>', views.CategoryList.as_view(), name='category_list'),
    path('question/list/', views.QuestionList.as_view(), name='question_list'),
    path('category_question/list/<int:category_id>', views.CategoryQuestionList.as_view(), name='category_question_list'),
    path('detail/<int:pk>/', views.QuestionDetail.as_view(), name='question_detail'),
    path('detail/<int:category_id>/<int:pk>/', views.QuestionDetail.as_view(), name='question_detail'),
    path('detail_img/<int:pk>/', views.ImageQuestionDetail.as_view(), name='question_detail_img'),
    path('detail_img/<int:category_id>/<int:pk>/', views.ImageQuestionDetail.as_view(), name='question_detail_img'),
    path('create/', views.QuestionCreateFormsetView.as_view(), name='question_create'),
    path('create_img/', views.ImageQuestionCreateFormsetView.as_view(), name='question_create_img'),
    path('update/<int:pk>', views.QuestionUpdateFormsetView.as_view(), name='question_update'),
    path('update_img/<int:pk>', views.ImageQuestionUpdateFormsetView.as_view(), name='question_update_img'),
    path('delete/<int:pk>', views.QuestionDeleteView.as_view(), name='question_delete'),
    path('delete_img/<int:pk>', views.ImageQuestionDeleteView.as_view(), name='question_delete_img'),
    path('question/add/<int:category_id>', views.QuestionAddView.as_view(), name='question_add'),
    path('question/add/<int:category_id>/<str:add_result>', views.QuestionAddView.as_view(), name='question_add'),
    path('question/exclusion/<int:category_id>', views.QuestionExclusionView.as_view(), name='question_exclusion'),
    path('question/exclusion/<int:category_id>/<str:exclusion_result>', views.QuestionExclusionView.as_view(), name='question_exclusion'),

    path('category/update/<int:group_id>/<int:pk>', views.CategoryUpdateView.as_view(), name='category_update'),
    path('category/create/<int:group_id>', views.CategoryCreateView.as_view(), name='category_create'),
    path('category/delete/<int:pk>', views.CategoryDeleteView.as_view(), name='category_delete'),

    path('category/sort/<int:pk>', views.CategoryGroupUpdateFormsetView.as_view(), name='category_sort'),

    

    
]

QuestionWeb/question/urls.py
from django.urls import path
from question import views

urlpatterns = [
    # 書籍
    path('question/<int:category_id>/<int:question_no>', views.QuestionView.as_view(), name='question'),
    path('category', views.CategoryView.as_view(), name='category'),
    path('answer_result/<int:category_id>/<int:question_id>/<int:question_no>/<str:question_type>/<int:choice_no>', views.AnswerResultView.as_view(), name='answer_result'),
    path('session_expire', views.SessionExpireView.as_view(), name='session_expire'),
    path('top', views.TopPageView.as_view(), name='top'),
    path('question/stop', views.QuestionStopView.as_view(), name='stop'),
    path('question/preparation', views.PreparationView.as_view(), name='preparation'),
    path('sample/answer/<str:question_type>/<int:question_id>', views.SampleAnswerView.as_view(), name='sample_answer'),
    path('help', views.HelpPageView.as_view(), name='help'),
]

QuestionWeb/question/models.py
from django.db import models

class CategoryGroup(models.Model):
    name = models.CharField('グループ名称', max_length=512, blank=False)

    def __str__(self):
        return self.name

def set_default_cateory_group():
    cateory_group, _ = CategoryGroup.objects.get_or_create(name='プリンセス別')
    return cateory_group.id

class Category(models.Model):
    name = models.CharField('カテゴリ名称', max_length=512, blank=False)
    category_no = models.PositiveSmallIntegerField(verbose_name='カテゴリNo.', default=1)
    CategoryGroup = models.ForeignKey(CategoryGroup, on_delete=models.CASCADE, default=set_default_cateory_group)
    img = models.ImageField(verbose_name='画像', upload_to='images/', null=True)

    def delete(self, using=None, keep_parents=False):
        self.img.delete()

        return super().delete(using, keep_parents)

    def save(self, *args, **kwargs):
        try:
            original_profile = Category.objects.get(pk=self.pk)
            if original_profile.img != self.img:
                original_profile.img.delete(save=False)

        except self.DoesNotExist:
            pass

        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

def set_default_disp_type():
    disp_type, _ = QuestionDispType.objects.get_or_create(name='左寄せ')
    return disp_type.id

class QuestionDispType(models.Model):
    name = models.CharField('表示形式名', max_length=512, blank=False)

    def __str__(self):
        return self.name


# Create your models here.
class Question(models.Model):
    body = models.CharField('本文（漢字）', max_length=1024)
    body_kana = models.CharField('本文（ひらがな）', max_length=1024, default="")
    Category = models.ManyToManyField(Category)
    question_no = models.PositiveSmallIntegerField(verbose_name='問題No.', default=0)
    answer_choice_no = models.PositiveSmallIntegerField(verbose_name='正解No.', default=1)
    ok_comment = models.CharField('解説（正解の場合）', max_length=1024, default="")
    ng_comment = models.CharField('解説（不正解の場合）', max_length=1024, default="")
    question_disp_type = models.ForeignKey(QuestionDispType, on_delete=models.SET_DEFAULT, default=set_default_disp_type)
    choice_type = models.CharField('選択肢のタイプ', max_length=1024, default="text")

    def __str__(self):
        return self.body

class TextChoice(models.Model):
    body = models.CharField('選択肢（漢字）', max_length=512)
    body_kana = models.CharField('選択肢（ひらがな）', max_length=1024, default="")
    Question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_no = models.PositiveSmallIntegerField(verbose_name='選択肢No.', default=1)

    def __str__(self):
        return self.body


class ImageQuestion(models.Model):
    body = models.CharField('本文（漢字）', max_length=1024)
    body_kana = models.CharField('本文（ひらがな）', max_length=1024, default="")
    Category = models.ManyToManyField(Category)
    question_no = models.PositiveSmallIntegerField(verbose_name='問題No.', default=0)
    answer_choice_no = models.PositiveSmallIntegerField(verbose_name='正解No.', default=1)
    ok_comment = models.CharField('解説（正解の場合）', max_length=1024, default="")
    ng_comment = models.CharField('解説（不正解の場合）', max_length=1024, default="")
    wrap_back_num = models.PositiveSmallIntegerField(verbose_name='1行の最大の選択肢数.', default=3)
    choice_type = models.CharField('選択肢のタイプ', max_length=1024, default="img")

    def __str__(self):
        return self.body

class ImageChoice(models.Model):
    img = models.ImageField(verbose_name = '画像', upload_to='images/', null=True)
    ImageQuestion = models.ForeignKey(ImageQuestion, on_delete=models.CASCADE)
    choice_no = models.PositiveSmallIntegerField(verbose_name='選択肢No.', default=1)

    def delete(self, using=None, keep_parents=False):
        self.img.delete()

        return super().delete(using, keep_parents)

    def save(self, *args, **kwargs):
        try:
            original_profile = ImageChoice.objects.get(pk=self.pk)
            if original_profile.img != self.img:
                original_profile.img.delete(save=False)

        except self.DoesNotExist:
            pass

        super().save(*args, **kwargs)

    def __str__(self):
        return self.body

QuestionWeb/question/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from question.models import Question, TextChoice, Category, ImageQuestion, CategoryGroup
import random
from django.http import HttpResponseRedirect
from django.shortcuts import reverse

# Create your views here.

QUESTION_MAX_QTY = 5

class TopPageView(TemplateView):
    template_name = "top.html"

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)

        sample_category = CategoryGroup.objects.get(name="サンプル問題").category_set.all().first() #サンプル問題カテゴリのみのはず。
        rand_int = random.randint(0, 1)

        # text優先
        if rand_int == 0:
            if sample_category.question_set.all().count() > 0:
                question_rand_int = rand_int = random.randint(0, sample_category.question_set.all().count() - 1)
                ctx['sample_question'] = sample_category.question_set.all()[question_rand_int]
                
            elif sample_category.imagequestion_set.all().count() > 0:
                question_rand_int = rand_int = random.randint(0, sample_category.imagequestion_set.all().count() - 1)
                ctx['sample_question'] = sample_category.imagequestion_set.all()[question_rand_int]

        #image優先
        elif rand_int == 1:
            if sample_category.imagequestion_set.all().count() > 0:
                question_rand_int = rand_int = random.randint(0, sample_category.imagequestion_set.all().count() - 1)
                ctx['sample_question'] = sample_category.imagequestion_set.all()[question_rand_int]
            elif sample_category.question_set.all().count() > 0:
                question_rand_int = rand_int = random.randint(0, sample_category.question_set.all().count() - 1)
                ctx['sample_question'] = sample_category.question_set.all()[question_rand_int]

        princess_group = CategoryGroup.objects.get(name="プリンセス別")
        ctx['princess_category_list'] = princess_group.category_set.all().order_by('category_no')

        difficulty_group = CategoryGroup.objects.get(name="難易度別")
        ctx['difficulty_category_list'] = difficulty_group.category_set.all().order_by('category_no')

        field_group = CategoryGroup.objects.get(name="分野別")
        ctx['field_category_list'] = field_group.category_set.all().order_by('category_no')

        return ctx


class QuestionView(TemplateView):
    template_name = "question_main.html"

    def get(self, request, **kwargs):
        
        question_no = kwargs.get('question_no')
        category_id = kwargs.get('category_id')

        question_qty = Category.objects.get(pk=category_id).question_set.all().count()
        question_qty += Category.objects.get(pk=category_id).imagequestion_set.all().count()

        if question_qty < QUESTION_MAX_QTY:
            return HttpResponseRedirect(reverse('preparation'))

        # セッション切れチェック
        if question_no == 1 and self.request.session.get('is_question_end', False) == False:
            self.request.session.clear() # 上限前に別カテゴリの問題に挑戦した場合はクリア

        elif question_no != 1 and not self.request.session.get('question_id_list', False):
            return HttpResponseRedirect(reverse('session_expire'))

        elif self.request.session.get('is_question_end', False):
            return HttpResponseRedirect(reverse('stop'))

        return super().get(request, **kwargs)

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)

        random_question_id_list = []
        category = Category.objects.get(pk=self.kwargs.get('category_id'))

        if not self.request.session.get('question_id_list', False):
            for q in category.question_set.all():
                random_question_id_list.append({'text' : q.id})
            
            for q in category.imagequestion_set.all():
                random_question_id_list.append({'img' : q.id})

            random.shuffle(random_question_id_list)
            
            self.request.session['question_id_list'] = random_question_id_list
            
        
        question_id_list = self.request.session.get('question_id_list')
        q_no = self.kwargs.get('question_no')

        rem_question_id_list = question_id_list[(q_no-1):]

        question_list = []

        for q_id_dic in rem_question_id_list:
            if 'text' in q_id_dic:
                question_list.append(Question.objects.get(pk=q_id_dic['text']))
            elif 'img' in q_id_dic:
                question_list.append(ImageQuestion.objects.get(pk=q_id_dic['img']))

        ctx['category'] = category

        ctx['question_list'] = question_list
        ctx['rem_res_cnt'] = QUESTION_MAX_QTY - self.request.session.get('res_cnt', 0)
        ctx['res_cnt'] = self.request.session.get('res_cnt', 0)

        return ctx

    def __get_text_question_id(self, random_question_id_list, category):
        question_list = category.question_set.all()

        for i in range(question_list.count()):
            rand_int = random.randint(0, question_list.count() - 1)
            rand_question = question_list[rand_int]

            if self.__is_selected(random_question_id_list, 'text', rand_question) == False:
                return rand_question.id
        
        return None

    def __get_img_question_id(self, random_question_id_list, category):
        question_list = category.imagequestion_set.all()

        for i in range(question_list.count()):
            rand_int = random.randint(0, question_list.count() - 1)
            rand_question = question_list[rand_int]

            if self.__is_selected(random_question_id_list, 'img', rand_question) == False:
                return rand_question.id
        
        return None

    
    def __is_selected(self, random_question_id_list, key, question):
        
        for rand_question_id_dict in random_question_id_list:
            if rand_question_id_dict.get(key) == question.id:
                return True

        return False

class QuestionStopView(TemplateView):
    template_name = "question_stop.html"

class CategoryView(TemplateView):
    template_name = "category.html"

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        
        category_list = Category.objects.all()

        ctx['category_list'] = category_list

        return ctx

class AnswerResultView(TemplateView):
    template_name = "question_comment.html"

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        
        if self.kwargs.get('question_type') == 'text':
            question = Question.objects.get(pk=self.kwargs.get('question_id'))
        elif self.kwargs.get('question_type') == 'img':
            question = ImageQuestion.objects.get(pk=self.kwargs.get('question_id'))

        answer_choice_no = question.answer_choice_no

        ctx['answer_choice_no'] = answer_choice_no
        ctx['choice_no'] = self.kwargs.get('choice_no')
        ctx['question'] = question
        ctx['category_id'] = self.kwargs.get('category_id')

        res_cnt = self.request.session.get('res_cnt', 0)
        res_cnt += 1
        self.request.session['res_cnt'] = res_cnt

        if res_cnt >= QUESTION_MAX_QTY:
            self.request.session['is_question_end'] = True

        return ctx

class SessionExpireView(TemplateView):
    template_name = "session_expire.html"

class PreparationView(TemplateView):
    template_name = "question_preparation.html"

class SampleAnswerView(TemplateView):
    template_name = "sample_answer.html"

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        
        if self.kwargs.get('question_type') == 'text':
            question = Question.objects.get(pk=self.kwargs.get('question_id'))
        elif self.kwargs.get('question_type') == 'img':
            question = ImageQuestion.objects.get(pk=self.kwargs.get('question_id'))

        ctx['princess_category'] = Category.objects.get(name="シンデレラ")
        ctx['question'] = question

        return ctx


class HelpPageView(TemplateView):
    template_name = "help.html"

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        
        

        return ctx

QuestionWeb/edit/templates/question/base.html
<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  {# Bootstrap4 で。#}
  <link rel="stylesheet"
        href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css"
        integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb"
        crossorigin="anonymous">
  <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
  <title>{% block meta_title %}{% endblock %}</title>
<body>

{% if messages %}
  {# Django のメッセージに記録している内容があればここで表示 #}
  <div class="container">
    <div class="row">
      <div class="col-12">
        <div class="messages mt-3">
          {% for message in messages %}
            <div class="alert alert-dismissable alert-{{ message.tags }}" data-alert="alert">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              {{ message }}
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
{% endif %}

<div class="container">
  <div class="row">
    <div class="col-12">
      <h1 class="mt-5">{% block page_title %}Base{% endblock %}</h1>
    </div>
  </div>
</div>
{% block extrahead %}
{% endblock %}
{% block content %}
{% endblock %}
{% block foot_scripts %}
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui-touch-punch/0.2.3/jquery.ui.touch-punch.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"
          integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh"
          crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"
          integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ"
          crossorigin="anonymous"></script>
{% endblock %}

{% block js %}
{% endblock %}

</body>
</html>

QuestionWeb/edit/templates/question/category_create.html
{% extends 'question/base.html' %}
{% block meta_title %}管理画面|カテゴリ新規作成{% endblock %}
{% block page_title %}管理画面|カテゴリ新規作成{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
  <div class="border" style="padding:10px;">
    <div class="row">
      <div class="col-12">
        <div class="card card-default">
          <div class="card-body">
            <form id="post_form" method="post" novalidate enctype="multipart/form-data">
              {% csrf_token %}
              {{ form|crispy }}
              <button class="btn btn-primary" type="submit">送信</button>
              &nbsp;&nbsp;
              <a class="btn btn-primary" href="{% url 'category_list' group_id %}" role="button">キャンセル</a>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block js %}

<script>
$(function(){
  $('#id_category_no').val({{ new_category_no }});
  $('#id_category_no').attr('readonly',true);
  $('#id_CategoryGroup').attr('disabled',true);
  
  
  $("option").each(function(i, o){
    if($(o).text() == "{{ group_name }}"){
      $(o).prop('selected', true);
    }
    else{
      $(o).removeAttr('selected')
    }
  });
  

  $('#post_form').submit(function(){
    $('#id_CategoryGroup').removeAttr('disabled');
  });
});
</script>

{% endblock %}

QuestionWeb/edit/templates/question/category_delete.html
{% extends 'question/base.html' %}
{% block meta_title %}管理画面|問題削除{% endblock %}
{% block page_title %}管理画面|問題削除{% endblock %}
{% block content %}
    
  <div class="container">
    <div class="row">
      <div class="col-12">
        <h1>削除確認画面</h1>
        <div class="card card-default">
          <div class="card-body">
            <form method="post">
            {% csrf_token %}
            <p>{{ object.name }}</p>
            <p>を削除しますか？</p>
            <input class="btn btn-danger" type="submit" value="削除する">
        </div>
      </div>
    </div>
  </div>
    </form>
{% endblock %}

QuestionWeb/edit/templates/question/category_list.html
{% extends 'question/base.html' %}
{% block meta_title %}管理画面|カテゴリ一覧{% endblock %}
{% block page_title %}管理画面|カテゴリ一覧{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
      <div class="col-12">
        <table class="table table-bordered table-striped">
            <thead class="thead-light">
                <tr><th style="width:10%">カテゴリNo.</th><th style="width:70%">カテゴリ名称</th><th style="width:20%">操作</th></tr>
            </thead>
            {% for category in object_list %}
            <tr>
                <td>{{ category.category_no }}</td>
                <td><a href="{% url 'category_question_list' category.pk %}">{{ category.name }}</a></td>
                <td>
                  <a class="btn btn-primary" href="{% url 'category_update' group_id category.pk %}" role="button">編集</a>
                  <a class="btn btn-danger" href="{% url 'category_delete' category.pk %}" role="button">削除</a>
                </td>
                
            </tr>
            {% endfor %}
        </table>
        <a class="btn btn-primary" href="{% url 'category_create' group_id %}" role="button">カテゴリ新規作成</a>
        <br>
        <br>
        <a class="btn btn-primary" href="{% url 'category_sort' group_id %}" role="button">カテゴリ並べ替え</a>
        <br>
        <br>
        <a class="btn btn-primary" href="{% url 'category_group_list' %}" role="button">管理トップに戻る</a>
      </div>
    </div>
</div>


{% endblock %}

QuestionWeb/edit/templates/question/category_update.html
{% extends 'question/base.html' %}
{% block meta_title %}管理画面|カテゴリ編集{% endblock %}
{% block page_title %}管理画面|カテゴリ編集{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
  <div class="border" style="padding:10px;">
    <div class="row">
      <div class="col-12">
        <div class="card card-default">
          <div class="card-body">
            <form id="post_form" method="post" novalidate enctype="multipart/form-data">
              {% csrf_token %}
              {{ form|crispy }}
              <button class="btn btn-primary" type="submit">送信</button>
              &nbsp;&nbsp;
              <a class="btn btn-primary" href="{% url 'category_list' object.CategoryGroup.id %}" role="button">キャンセル</a>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block js %}

<script>
$(function(){
  $('#id_CategoryGroup').attr('disabled',true);

  $('#post_form').submit(function(){
    $('#id_CategoryGroup').removeAttr('disabled');
  });
});
</script>

{% endblock %}

QuestionWeb/edit/templates/question/imagequestion_delete.html
{% extends 'question/base.html' %}
{% block meta_title %}管理画面|問題削除{% endblock %}
{% block page_title %}管理画面|問題削除{% endblock %}
{% block content %}
    
  <div class="container">
    <div class="row">
      <div class="col-12">
        <h1>削除確認画面</h1>
        <div class="card card-default">
          <div class="card-body">
            <form method="post">
            {% csrf_token %}
            <p>{{ imagequestion.body }}</p>
            <p>を削除しますか？</p>
            <input class="btn btn-danger" type="submit" value="削除する">
        </div>
      </div>
    </div>
  </div>
    </form>
{% endblock %}

QuestionWeb/edit/templates/question/question_create_form.html
{% extends "question/question_form.html" %}
{% block meta_title %}管理画面|問題新規作成{% endblock %}
{% block page_title %}管理画面|問題新規作成{% endblock %}
{% block js %}
<script>
$(function(){
 
    set_choice_no();

});
</script>

{{ block.super }}

{% endblock %}

QuestionWeb/edit/templates/question/question_form_img.html
{% extends 'question/base.html' %}
{% load bootstrap4 %}
{% load crispy_forms_tags %}
{% load static %}
{% load crispy_forms_tags %}
{% block meta_title %}管理画面|問題編集{% endblock %}
{% block page_title %}管理画面|問題編集{% endblock %}

{% block extrahead %}
    
{% endblock %}

{% block content %}
<div class="container">
    <div class="border" style="padding:10px;">
        <form method="post" enctype="multipart/form-data" id="post_form">
            {% csrf_token %}
            {{ form.management_form }}

            <div class="form-row">
                <div class="form-group col-sm-1">
                </div>

                <div class="form-group col-sm-10">
                    {{ form|crispy }}
                </div>
                <div class="form-group col-sm-1">
                </div>
            </div>

            <ul style="list-style-type: none; padding : 0;" id="choice_list" class="choice_list">
            {% for inline in inlines %}
                {{ inline.management_form }}
                    {% for line in inline %}
                    <li id="li_choice_{{ forloop.counter }}">
                        <div class="form-row">
                            <div class="form-group col-sm-1">
                            </div>

                            <div class="form-group col-sm-10">
                                <div class="border" style="padding:30px;">
                                    {{ line }}
                                </div>
                            </div>
                            <div class="form-group col-sm-1">
                            </div>
                            
                        </div>
                    </li>
                    {% endfor %}
            {% endfor %}
            </ul>
            <button id="choice_add_btn" type="button" class="btn btn-primary">選択肢を追加</button>
            </div>
            <button class="btn btn-primary" type="submit">送信</button>
            <a class="btn btn-primary" href="{% url 'category_group_list' %}" role="button">キャンセル</a>
            
        </form>
    
    
  </div>
{% endblock %}

{% block js %}

<script>

function set_choice_no(){
    var choice_no = 1;

    
    $("[id^='li_choice_']").each(function(i, o){
        var delete_check = $(o).find("input[type='checkbox']" + "[id^='id_imagechoice_set-']").prop("checked");

        if(typeof delete_check === "undefined" || delete_check == false){
            $(o).find("input[type='number']" + "[id^='id_imagechoice_set-']").val(choice_no);
            choice_no++;
        }
        
    });
}

$(function(){
    
    $(document).on('change', "input[type='checkbox']" + "[id^='id_imagechoice_set-']", function() {
        if($(this).prop("checked")){

            var enable_choice_qty = 0;
            $("#choice_list > li").each(function(i, o){
                if($(o).find("input[type='checkbox']").prop("checked") === false){
                    enable_choice_qty++;    
                }
                
            });

            if(enable_choice_qty < 2){
                $(this).removeAttr('checked').prop('checked', false).change();
                alert("選択肢は最低でも2つ必要です。");
            }
            else{
                $(this).parent().addClass("bg-secondary");
            }

            //bg-secondary
        }
        else{
            $(this).parent().removeClass("bg-secondary");
        }

        set_choice_no();
    });

    $('#choice_add_btn').click(function() {

        var choice_qty = 0;

        $("#choice_list > li").each(function(i, o){
            choice_qty++;
        });
        var clone = $("#choice_list > [id='li_choice_" + choice_qty + "']").clone();


        clone_html = clone.prop('outerHTML');

        var latest_choice_no = choice_qty - 1; //0から始まるため
        var formset_id = 'set-' + latest_choice_no;
        var li_choice_id = 'li_choice_' + choice_qty;

        var new_choice_html = clone_html.replace(new RegExp(formset_id, "g"), 'set-' + choice_qty); //0から始まるので、choice_qtyがそのまま新しいIDになる
        var new_choice_html = new_choice_html.replace(new RegExp(li_choice_id, "g"), 'li_choice_' + (choice_qty + 1));

        $('#choice_list').append(new_choice_html);
        $('#id_imagechoice_set-TOTAL_FORMS').val(choice_qty + 1);

        set_choice_no();

    });

    $("#choice_list").sortable({
        axis: "y", // ドラッグの方向を縦に固定
        "opacity": 0.5, // ドラッグ中の透明度
        "update": function(event,ui){ // ドラッグ完了後のコールバック
            set_choice_no();
        }
    });

    var b = $("#choice_list > input[type='hidden']").each(function(i, o){
      //コンソールにインデックス番号とテキストを出力する
        $(o).prop('outerHTML');
    });

    var a = $('.choice_list > li').sort(function(a, b){
        var num1 = $(a).find("input[type='number']").val();
        var num2 = $(b).find("input[type='number']").val();

        return num1 - num2;
    });

    $('.choice_list > li').each(function(i, o){
        $(o).find("input[type='number']").attr('readonly',true);
    });

    $('#choice_list').html(b);
    $('#choice_list').append(a);

    $('#post_form').submit(function(){
        var choice_qty = 0;

        $("#choice_list > li").each(function(i, o){
            choice_qty++;
        });

        answer_choice_no = $("#id_answer_choice_no").val();

        if( answer_choice_no > choice_qty || answer_choice_no == 0){
            alert("正解Noに該当する選択肢がありません。");
            return false;
        }


        if( $('#id_wrap_back_num').val() <= 0){
            alert("1行の最大選択肢数は1以上にしてください。");
            return false;
        }
        return true;
    });
});

</script>

{% endblock %}